AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minecraft Hibernated Server - Network Infrastructure (Default VPC Support)'

Parameters:
  StackName:
    Type: String
    Description: Parent stack name for resource naming

Resources:
  # This template provides default VPC discovery
  # In practice, most users will use their default VPC
  
  # VPC Discovery - Get default VPC information
  VPCInfo:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${StackName}-vpc'
        - Key: Purpose
          Value: minecraft-hibernated-server

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${StackName}-igw'

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPCInfo
      InternetGatewayId: !Ref InternetGateway

  # Public Subnet
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCInfo
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${StackName}-public-subnet'

  # Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCInfo
      Tags:
        - Key: Name
          Value: !Sub '${StackName}-public-rt'

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

Outputs:
  VpcId:
    Description: VPC ID for use by other stacks
    Value: !Ref VPCInfo
    Export:
      Name: !Sub '${StackName}-VPC'

  PublicSubnetId:
    Description: Public subnet ID for EC2 instances
    Value: !Ref PublicSubnet
    Export:
      Name: !Sub '${StackName}-PublicSubnet'

  InternetGatewayId:
    Description: Internet Gateway ID
    Value: !Ref InternetGateway
    Export:
      Name: !Sub '${StackName}-IGW'